apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: task-manager
data:
  USER_SERVICE_URL: "http://user-service:3001"
  TASK_SERVICE_URL: "http://task-service:3002"
  NOTIFICATION_SERVICE_URL: "http://notification-service:3003"
  AWS_REGION: "us-east-1"
  AWS_ENDPOINT_URL: "http://localstack:4566"
  NODE_ENV: "production"